# Generated by Django 6.0 on 2026-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_free_plan_used',
            field=models.BooleanField(default=False, verbose_name='Plano Gratuito Ativado'),
        ),
    ]
