# Generated by Django 6.0 on 2026-01-15 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_free_plan_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'Dados Bancários do Usuário', 'verbose_name_plural': 'Dados Bancários dos Usuários'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platformbankdetails',
            options={'verbose_name': 'Conta da Plataforma', 'verbose_name_plural': 'Contas da Plataforma'},
        ),
        migrations.AlterModelOptions(
            name='roulette',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userlevel',
            options={},
        ),
        migrations.AddField(
            model_name='deposit',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome/ID do Comprovativo'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(choices=[('bank', 'Banco (Angola)'), ('pix', 'PIX (Brasil)'), ('trc20', 'Cripto (USDT TRC20)')], default='bank', max_length=10, verbose_name='Método'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='IBAN',
            field=models.CharField(max_length=100, verbose_name='IBAN / Chave PIX'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_holder_name',
            field=models.CharField(max_length=100, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Disponível'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subsidy_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo de Subsídios'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='level',
            name='cycle_days',
            field=models.IntegerField(verbose_name='Dias de Ciclo'),
        ),
        migrations.AlterField(
            model_name='level',
            name='daily_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganho Diário'),
        ),
        migrations.AlterField(
            model_name='level',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Custo de Ativação'),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(upload_to='level_images/', verbose_name='Ícone/Imagem'),
        ),
        migrations.AlterField(
            model_name='level',
            name='monthly_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ganho Mensal'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='IBAN',
            field=models.CharField(max_length=100, verbose_name='IBAN / Chave PIX / Carteira'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='account_holder_name',
            field=models.CharField(max_length=100, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Nome do Banco/Rede'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='deposit_instruction',
            field=models.TextField(verbose_name='Instrução Depósito'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='history_text',
            field=models.TextField(verbose_name="Texto 'Sobre'"),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_link',
            field=models.URLField(help_text='Link para suporte.', verbose_name='Link do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='withdrawal_instruction',
            field=models.TextField(verbose_name='Instrução Saque'),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='spin_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='roulette',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='prizes',
            field=models.CharField(default='0,100,500', help_text='Lista de prêmios separados por vírgula. Ex: 0,500,1000,5000', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='earnings',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.level'),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userlevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20, verbose_name='Status'),
        ),
    ]
