# Generated by Django 6.0 on 2026-01-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bankdetails_options_alter_level_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(choices=[('bank', 'Banco (IBAN)'), ('pix', 'PIX'), ('usdt', 'USDT (TRC20)')], default='bank', max_length=10, verbose_name='Método Escolhido'),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='withdrawal_details',
            field=models.TextField(blank=True, help_text='Ex: IBAN ou Chave PIX usada no momento do saque', null=True, verbose_name='Dados do Recebimento'),
        ),
    ]
