# Generated by Django 6.0 on 2026-01-15 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_withdrawal_method_withdrawal_withdrawal_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platformbankdetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='platformsettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roulettesettings',
            options={},
        ),
        migrations.AlterModelOptions(
            name='withdrawal',
            options={},
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='IBAN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='account_holder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='proof_of_payment',
            field=models.ImageField(upload_to='deposit_proofs/'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='level',
            name='cycle_days',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='level',
            name='daily_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='level',
            name='deposit_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='level',
            name='image',
            field=models.ImageField(upload_to='level_images/'),
        ),
        migrations.AlterField(
            model_name='level',
            name='monthly_gain',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='IBAN',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='account_holder_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platformbankdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='whatsapp_link',
            field=models.URLField(verbose_name='Link do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='roulettesettings',
            name='prizes',
            field=models.CharField(help_text='Ex: 0,500,1000', max_length=255),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Recusado', 'Recusado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='withdrawal_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
