# Generated by Django 6.0 on 2026-01-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bankdetails_options_alter_deposit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='method',
            field=models.CharField(max_length=50),
        ),
    ]
