# Generated by Django 6.0 on 2026-01-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_deposit_payment_method_alter_withdrawal_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='payment_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
